<?php

// 98 

  /*
    Cookies

    - Examples
    --- Popup
    --- Custom Settings
    --- Remember Me => Login

    - setcookie(Name[Required], Value, Expire, Path, Domain, Secure, HTTP_Only);
    --- Name
    --- Value
    --- Expire
    --- Path
    --- Domain
    --- Secure
    --- HTTP_Only
  */

  setcookie("style", "dark", time() + 60 * 60 * 24 * 30);

  echo "<br>";
  echo "<br>";
  echo "<br>";
  echo "<br>";
  ?>
  <?php

// 99

/*
  Cookies

  - setcookie(Name[Required], Value, Expire, Path, Domain, Secure, HTTP_Only);
  --- Name
  --- Value
  --- Expire
  --- Path
  --- Domain
  --- Secure
  --- HTTP_Only

  Important
  - DO NOT Store Sensitive Information
  - Not Everything Saved To Cookies
*/

setcookie("style", "dark", time() + 60 * 60 * 24 * 30, "/");
setcookie("popup", "done", strtotime("+1 month"));

echo "<pre>";
print_r($_COOKIE);
echo "</pre>";

echo $_COOKIE["style"];

  echo "<br>";
  echo "<br>";
  echo "<br>";
  echo "<br>";
  ?>
  <?php

// 100

/*
  Cookies
  - Modify
  - Delete
  - Add Array
*/

// setcookie("style[color]", "red");
// setcookie("style[font]", "Tahoma");
// setcookie("style[layout]", "boxed");

// echo "<pre>";
// print_r($_COOKIE);
// echo "</pre>";

// if (isset($_COOKIE["style"])) {
//   echo $_COOKIE["style"]["font"];
// }
//   echo "<br>";
//   echo "<br>";
//   echo "<br>";
//   echo "<br>";
  ?>
<?php 

// 101

  /*
    Cookies
    - Practice
  */
if (isset($_COOKIE["background"])){
    echo "<style>body{background-color:".$_COOKIE["background"]."}</style>";
}
if($_SERVER["REQUEST_METHOD"]=="POST"){
    setcookie("background",$_POST["bg-color"],strtotime("+1 year"));
    header("Location: " . $_SERVER["REQUEST_URI"]);
    exit();
}

?>

<form action="" method="POST">
  <input type="color" name="bg-color">
  <input type="submit" value="Choose Color">
</form>
<?php 
// session
// 102

/*
  Sessions
  - Session Is Stored On The Server
  - Session Store Only A User Key In Cookie To Know Its You
  - Key Are Generated By PHP Engine So Its Almost Impossible To Guess
  - You Need To Add It Before Any Output
*/

session_start();

$_SESSION['name'] = "Ahmed";
$_SESSION['id'] = 1005;

echo '<pre>';
print_r($_SESSION);
echo '</pre>';

echo '<a href="test.php">Test</a>';

  echo "<br>";
  echo "<br>";
  echo "<br>";
  echo "<br>";
?>
<?php

 // 103
 
/*
  Sessions
  - Advanced Information
  - Edit
  - Views Count
*/

// session_id("lkjsdklfjksdfsdf");

session_start();

// echo session_id();

$_SESSION['name'] = "Elzero";

isset($_SESSION['views']) ? $_SESSION['views']++ : $_SESSION['views'] = 1;

echo "Hello " . $_SESSION['name'] . " Views Count Is " . $_SESSION['views'];

echo '<a href="about.php">About</a>';
  echo "<br>";
  echo "<br>";
  echo "<br>";
  echo "<br>";
?>